version: 2

workflows:
  version: 2
  ci:
    jobs:
      - build_test
      - deploy:
          requires:
            - build_test
          filters:
            branches:
              only:
                - master
                - staging

jobs:
  build_test:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: setup
          command: |
            sudo apt update
            sudo apt install nginx
            sudo service nginx start
            
          

