version: 2

workflows:
  version: 2
  ci:
    jobs:
      - build_test
jobs:
  build_test:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Check required environment variables
          command: |
            required_env=(
              "DOCKERHUB_USERNAME"
              "DOCKERHUB_PASSWORD"
            )
            
      - run:
          name: setup
          command: |
            apt update
            apt install nginx -y
            service nginx start
            apt install docker-compose -y
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Login to docker hub
          command: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Build Docker image
          command: docker build -t $DOCKERHUB_USERNAME/project1:1.1 .
      - run:
          name: Tag Docker image
          command: docker tag $DOCKERHUB_USERNAME/project1:1.1 $DOCKERHUB_USERNAME/project1:1.1
      - run:
          name: Push image $IMAGE_TAG to docker registry
          command: docker push $DOCKERHUB_USERNAME/project1:1.1
            
          

