version: 2

workflows:
  version: 2
  ci:
    jobs:
      - build_test
jobs:
  build_test:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: setup
          command: |
            apt update
            apt install nginx
            service nginx start
            
          

